name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
      - issue-*
      - fb_*
  push:
    branches:
      - master
      - issue-*
      - fb_*

  workflow_dispatch: # Allows manually triggering this workflow

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Browsers
        uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-edge@latest

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/reports

# Separate workflow section for smoke_job
---
name: Smoke Job

on:
  workflow_dispatch: # Enables manual triggering of this workflow after build_and_test

jobs:
  smoke_job:
    name: Smoke Tests
    runs-on: ubuntu-latest

    needs: build_and_test # Ensures smoke_job can only run after build_and_test is successful

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Smoke Tests (Chrome)
        run: mvn clean test -Drunmode=headless -Dbrowser=chrome -Dgroups=SWAG_LABS_SMOKE -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3