name: Publish Test Reports

on:
  workflow_dispatch:
  push:
    branches:
      - fb_pages

jobs:
  build_and_test:
    name: Run Tests and Publish Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test -Dgroups=SWAG_LABS_SMOKE,SWAG_LABS_REGRESSION,SWAG_LABS_E2E -Ddataproviderthreadcount=3

      - name: Verify Report Directory
        run: ls target/surefire-reports || echo "Report directory not found"

      - name: Generate Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/TEST-*.xml"
        if: always()

  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs: build_and_test
    if: always()  # Publish even if tests fail to capture failure reports
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Reports
        run: |
          mkdir -p reports
          cp -r target/surefire-reports/* reports/

      - name: Configure Git for Publishing
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Publish Reports to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
