name: Smoke Job

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  smoke_job_chrome_headless:
    name: Smoke Tests Chrome Headless
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
        continue-on-error: false # Fails if the artifact is not available, meaning build_and_test didn't complete

      - name: Run Smoke Tests (Chrome)
        run: mvn clean test -Drunmode=headless -Dbrowser=chrome -Dgroups=SWAG_LABS_SMOKE -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3
