name: UI test execution

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - issue-*
      - fb_*
  push:
    branches:
      - master
      - issue-*
      - fb_*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install Browsers
        uses: browser-actions/setup-chrome@latest
      - uses: browser-actions/setup-firefox@latest
      - uses: browser-actions/setup-edge@latest

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/reports

  smoke_job_chrome_headless:
    name: Smoke Tests Chrome Headless
    runs-on: ubuntu-latest
    needs:
      - build_and_test
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Smoke Tests (Chrome)
        run: mvn clean test -Drunmode=headless -Dbrowser=chrome -Dgroups=SWAG_LABS_SMOKE -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  smoke_job_firefox_headless:
    name: Smoke Tests Firefox Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Smoke Tests (Firefox)
        run: mvn clean test -Drunmode=headless -Dbrowser=firefox -Dgroups=SWAG_LABS_SMOKE -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  smoke_job_msedge_headless:
    name: Smoke Tests MS Edge Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Smoke Tests (MS Edge)
        run: mvn clean test -Drunmode=headless -Dbrowser=msedge -Dgroups=SWAG_LABS_SMOKE -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  regression_job_chrome_headless:
    name: Regression Tests Chrome Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Regression Tests (Chrome)
        run: mvn clean test -Drunmode=headless -Dbrowser=chrome -Dgroups=SWAG_LABS_REGRESSION -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  regression_job_firefox_headless:
    name: E2E Tests Firefox Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Regression Tests (Firefox)
        run: mvn clean test -Drunmode=headless -Dbrowser=firefox -Dgroups=SWAG_LABS_REGRESSION -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  regression_job_msedge_headless:
    name: Regression Tests MS Edge Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run Regression Tests (MS Edge)
        run: mvn clean test -Drunmode=headless -Dbrowser=msedge -Dgroups=SWAG_LABS_REGRESSION -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  E2E_job_chrome_headless:
    name: E2E Tests Chrome Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run E2E Tests (Chrome)
        run: mvn clean test -Drunmode=headless -Dbrowser=chrome -Dgroups=SWAG_LABS_E2E -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  E2E_job_firefox_headless:
    name: E2E Tests Firefox Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run E2E Tests (Firefox)
        run: mvn clean test -Drunmode=headless -Dbrowser=firefox -Dgroups=SWAG_LABS_E2E -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3

  E2E_job_msedge_headless:
    name: E2E Tests MS Edge Headless
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: target

      - name: Run E2E Tests (MS Edge)
        run: mvn clean test -Drunmode=headless -Dbrowser=msedge -Dgroups=SWAG_LABS_E2E -Dtestng.parallel=methods -DthreadPoolSize=3 -Ddataproviderthreadcount=3